apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prilozhuha
  name: prilozhuha
spec:
  replicas: 1 
  progressDeadlineSeconds: 222
  selector:
    matchLabels:
      app: prilozhuha
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prilozhuha
    spec:
      containers:
      - image: w1ckeds1ck/prilozhuha:latest
        name: prilozhuha
        env:
          - name: POSTGRES_DB_USER
            value: "postgres"
          - name: POSTGRES_DB_PASSWORD
            value: "postgres"
          - name: POSTGRES_DB_HOST
            value: "postgres"
          - name: POSTGRES_DB_PORT
            value: "5432"
          - name: POSTGRES_DB_DATABASE
            value: "postgres"
          - name: TARGET_SIMULATOR_HOST
            value: "https://simple-flask-website-simulator.herokuapp.com"
          - name: KAFKA_HOST_PORT
            value: "my-kafka-headless.default.svc.cluster.local:9092"
          - name: KAFKA_TOPIC
            value: "metric"
          - name: KAFKA_CLIENT_ID
            value: "metric"
          - name: KAFKA_GROUP_ID
            value: "metric"
        resources:
          limits:
            memory: "200Mi"
            cpu: "30m"
          requests:
            memory: "40Mi"
            cpu: "5m"
status: {}